[changelog]

header = "# Changelog\n\nВсе существенные изменения в этом проекте будут записаны в этом файле.\n\n"

footer = "<!-- сгенерировано с помощью git-cliff -->"

[git]

commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Новые функции" },
    { message = "^fix", group = "<!-- 1 -->Исправления ошибок" },
    { message = "^doc", group = "<!-- 3 -->Документация" },
    { message = "^perf", group = "<!-- 4 -->Улучшение производительности" },
    { message = "^refactor", group = "<!-- 2 -->Рефакторинг" },
    { message = "^style", group = "<!-- 5 -->Форматирование кода" },
    { message = "^test", group = "<!-- 6 -->Тестирование" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore", group = "<!-- 7 -->Рутина" },
    { message = "^ci", group = "<!-- 8 -->CI/CD" },
    { body = ".*security", group = "<!-- 9 -->Безопасность" },
    { message = "^revert", group = "<!-- 10 -->Откат изменений" },
    { message = ".*", group = "<!-- 11 -->Прочее" },
]